#Permission level required
sudo: required
#services required
services:
  - docker
#commands/steps to be executed before to run our tests which are build image with tag  (for convinience)
#for us we have only tests for client. project and specify build context as client directory
before_install:
 - docker build -t ballamouli91/docker-react-complex-test:latest -f ./client/Dockerfile.dev ./client
#script section suppose to conatain all commands to run our test suite, if test suite exit code is zero then travis feel tests are passed
# as we know that npm run tests just sites and hangs for waiting from us (default watchmode), so we need pass extra comand -- -- coverage to run tests and exits out of terminal

script:
#tests run with coverage
- docker run ballamouli91/docker-react-comlex-test npm run test -- --coverage

#after our tests are passed, we need to build our prod images(client/nginx/worker/server) and push to dockerhub
after_success:
- docker build -t ballamouli91/docker-react-complex-multi-client ./client
- docker build -t ballamouli91/docker-react-complex-multi-nginx ./nginx
- docker build -t ballamouli91/docker-react-complex-multi-server ./server
- docker build -t ballamouli91/docker-react-complex-multi-worker ./worker
#after images are build, we need to login docker and push images
##login docker cli and use login id and password from travis environment variables $DOCKER_PASSWORD & $DOCKER_ID
#For docker login travis does not really have a support for prompt/multistep wizard to login docker,so we will be using complex command for login (instead docker login)
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# push images
- docker push ballamouli91/docker-react-complex-multi-client
- docker push ballamouli91/docker-react-complex-multi-nginx
- docker push ballamouli91/docker-react-complex-multi-server
- docker push ballamouli91/docker-react-complex-multi-worker

deploy:
 provider: elasticbeanstalk
 #app name,env and region name of Beanstalk
 region: "us-west-1"
 app: "multi-docker"
 env: "multidocker-env"
#s3 bucket name where travis will put code and image in AWS, Which automatically created when we create elasticbeanstalk
 bucket_name: "elasticbeanstalk-us-west-1-12252555"
 #bucket path is app name
 bucket_path: "docker-multi"
 on:
  branch: master
#update API keys for travis to communicate with AWS EBS, access it from travis secrets
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
 

