version: '3'
services:
  nginx:
    #restart policy to always wnated to make sure the nginx up to take requests
   restart: always
   build:
    dockerfile: Dockerfile.dev
    context: ./nginx
   ports:
    - '3050:80'
  postgres:
   image: 'postgres:latest'
  redis:
   image: 'redis:latest'
  #CHAnGED NAME OF SERVER AS API FOR NGINX ROUTING
  api:
   build:
    dockerfile: Dockerfile.dev
    context: ./server
   volumes:
    - /app/node_modules
    - ./server:/app
   environment:
      #anytime we are calling pariclaur service host, we cna access it by just calling that service name
    - REDIS_HOST=redis
    #default port for redis
    - REDIS_PORT=6379
     #defautl values for postgres
    - PGUSER=postgres
    #service name
    - PGHOST=postgres
    #degault databse of postgres
    - PGDATABASE=postgres
    #default password for psogres 
    - PGPASSWORD=postgres_password
    #default port for postgres
    - PGPORT=5432
  client:
   build:
    dockerfile: Dockerfile.dev
    context: ./client
   volumes:
    - /app/node_modules
    - ./client:/app
  worker:
   build:
    dockerfile: Dockerfile.dev
    context: ./worker
   volumes:
    - /app/node_modules
    - ./worker:/app

